#: import MapSource kivy_garden.mapview.MapSource
#: import MDTextField kivymd.uix.textfield.textfield.MDTextField
#: import MDSearchBar kivymd.uix.search.search.MDSearchBar

MDRelativeLayout:
    MapView:
        lat: 1.296
        lon: 103.776
        zoom: 16

        MapMarkerPopup:
            lat:1.296
            lon: 103.776

            popup_size:dp(230),dp(130)
            Bubble:
                MDBoxLayout:
                    padding: "4dp"
                    MDLabel:
                        text: "You in here"
                        markup: True
                        halign: "center"

    MDTextField:
        mode: "filled"

        MDTextFieldLeadingIcon:
            icon: "magnify"
