#: import MapSource kivy_garden.mapview.MapSource
#: import MDTextField kivymd.uix.textfield.textfield.MDTextField

<Demo>:
    Screen:
        name: "map"
        MapView:
            lat: 1.296
            lon: 103.776
            zoom: 16

        MapMarkerPopup:
            lat: 1.296
            lon: 103.776

            popup_size:dp(230),dp(130)
            Bubble:
                MDBoxLayout:
                    padding: "4dp"
                    MDLabel:
                        text: "You in here"
                        markup: True
                        halign: "center"
        
        MDButton:
            text: "go to screen 1"
            pos_hint: {"center_y": .5, "center_x": .1}
            on_release: root.current = "screen1"
    
    Screen:
        name: "screen1"
        MDLabel:
            text: 'screen1'
            halign: 'center'
        MDButton:
            text: "go to screen 2"
            pos_hint: {"center_y": .5, "center_x": .4}
            on_release: root.current = "screen2"

    Screen:
        name: "screen2"
        MDLabel:
            text: 'screen2'
            halign: 'center'
        MDButton:
            text: "go to screen 1"
            pos_hint: {"center_y": .5, "center_x": .4}
            on_release: root.current = "map"

