#: import MDScreenManager kivymd.uix.screenmanager.MDScreenManager
#: import MDScreen kivymd.uix.screen.MDScreen

MDScreen:
    md_bg_color: self.theme_cls.primaryColor

    MDLabel:
        adaptive_size: True
        pos_hint: {"center_x": .5, "center_y": .5}
        text: "Where are you now?"
        allow_selection: True
        padding: "4dp", "4dp"

    MDTextField:
        mode: "filled"

        MDTextFieldLeadingIcon:
            icon: "magnify"

    